feat: removed n.sh and change zsh_nvm

diff --git a/bash-scripts/zsh_nvm b/bash-scripts/zsh_nvm
--- a/bash-scripts/zsh_nvm
+++ b/bash-scripts/zsh_nvm
@@ -1,4 +1,23 @@
-function setNpmrc(){
+#!/bin/bash
+
+# Source nvm
+if [ -z "$NVM_DIR" ]; then
+  export NVM_DIR="$HOME/.nvm"
+fi
+
+if [ -s "$NVM_DIR/nvm.sh" ]; then
+  . "$NVM_DIR/nvm.sh"
+else
+  echo "Error: nvm.sh not found in $NVM_DIR"
+  exit 1
+fi
+
+# Bash completion (optional)
+if [ -s "$NVM_DIR/bash_completion" ]; then
+  . "$NVM_DIR/bash_completion"
+fi
+
+function setNpmrc() {
   if [ ! -f .npmrc ]; then
     touch .npmrc
     echo "engine-strict=true" > .npmrc
@@ -7,35 +26,32 @@ function setNpmrc(){
 
 setNpmrc
 
-function getNodeVersionFromPackageJson(){
+function getNodeVersionFromPackageJson() {
   if [ -f package.json ]; then
     node_version=$(jq -r '.engines.node' package.json)
     if [ -z "$node_version" ]; then
-      echo "${tred}package.json has no node string${treset}"
+      echo "package.json has no node string"
       exit 1
     fi
     new=$(echo $node_version | sed 's/[^0-9.]//g')
     echo $new
   else
-    # echo "package.json not found"
     exit 1
   fi
 }
 
-autoload -U add-zsh-hook
-load-nvmrc() {
+function load_nvmrc() {
   local node_version="$(nvm version)"
   node_package=$(getNodeVersionFromPackageJson)
   echo "node_version: $node_version"
   echo "node_package: $node_package"
   if [ "$node_version" != "$node_package" ]; then
-    # check if node version is installed
-    nvm install $node_package
-    nvm use $node_package
+    nvm install "$node_package"
+    nvm use "$node_package"
   fi
 }
-
 if [ -f package.json ]; then
-  add-zsh-hook chpwd load-nvmrc
-  load-nvmrc
+  load_nvmrc
+else
+  echo "No package.json found"
 fi
